export const tweetData = [
  {userName: 1, timeStamp: "16/09/2022", content: "A tree needs to be your friend if you're going to paint him. You can create beautiful things - but you have to see them in your mind first. So often we avoid running water, and running water is a lot of fun.",
  comments: [] },
  {userName: 2, timeStamp: "16/09/2022", content: "A tree needs to be your friend if you're going to paint him. You can create beautiful things - but you have to see them in your mind first. So often we avoid running water, and running water is a lot of fun.",
  comments: [] },
  {userName: 3, timeStamp: "16/09/2022", content: "A tree needs to be your friend if you're going to paint him. You can create beautiful things - but you have to see them in your mind first. So often we avoid running water, and running water is a lot of fun.",
  comments: ["Green power ftw!"] },
  {userName: 4, timeStamp: "16/09/2022", content: "A tree needs to be your friend if you're going to paint him. You can create beautiful things - but you have to see them in your mind first. So often we avoid running water, and running water is a lot of fun.",
  comments: [] },
  {userName: 5, timeStamp: "16/09/2022", content: "A tree needs to be your friend if you're going to paint him. You can create beautiful things - but you have to see them in your mind first. So often we avoid running water, and running water is a lot of fun.",
  comments: [] },
  {userName: 6, timeStamp: "16/09/2022", content: "A tree needs to be your friend if you're going to paint him. You can create beautiful things - but you have to see them in your mind first. So often we avoid running water, and running water is a lot of fun.",
  comments: [] },
  {userName: 7, timeStamp: "16/09/2022", content: "A tree needs to be your friend if you're going to paint him. You can create beautiful things - but you have to see them in your mind first. So often we avoid running water, and running water is a lot of fun.",
  comments: [] },
  {userName: 8, timeStamp: "16/09/2022", content: "A tree needs to be your friend if you're going to paint him. You can create beautiful things - but you have to see them in your mind first. So often we avoid running water, and running water is a lot of fun.",
  comments: [] },
]